### ISSUE TITLE
로또 기능

### ISSUE THREAD

**Issue by Hyyena** [Hyyena/woowacourse_java-lotto-6#1]
## 1. Feature

- 로또 기능

## 2. Tasks

- [x] 로또 번호 생성 기능
    - [x] 로또 번호는 6개의 숫자
        - [x] 6개의 숫자가 아닌 경우 예외 처리
        - [x] 아무 로또 번호도 없는 경우 예외 처리
    - [x] 로또 번호는 `1~45` 사이의 랜덤 숫자
        - [x] `1~45` 사이의 랜덤 숫자가 아닌 경우 예외 처리
    - [x] 로또 번호는 중복되지 않음
        - [x] 중복된 숫자가 있는 경우 예외 처리

## 3. Test

- [x] 테스트 코드 작성 여부
