### ISSUE TITLE
구입 기능

### ISSUE THREAD

**Issue by Hyyena** [Hyyena/woowacourse_java-lotto-6#3]
## 1. Feature

- 구입 기능

## 2. Tasks

- [x] 로또 구입 기능
    - [x] 구입 금액에 해당하는 만큼 로또 발행
    - [x] 로또 1장의 가격은 1,000원
        - [x] 1,000원으로 나누어 떨어지지 않는 경우 예외 처리

## 3. Test

- [x] 테스트 코드 작성 여부
