### ISSUE TITLE
수익률 기능

### ISSUE THREAD

**Issue by Hyyena** [Hyyena/woowacourse_java-lotto-6#4]
## 1. Feature

- 수익률 기능

## 2. Tasks

- [x] 수익률 계산 기능
  - [x] `수익률 = (당첨금액 - 로또 구입 금액) / 로또 구입 금액`
  - [x] 수익률은 소수점 둘째 자리에서 반올림

## 3. Test

- [x] 테스트 코드 작성 여부
