### ISSUE TITLE
입력 기능

### ISSUE THREAD

**Issue by Hyyena** [Hyyena/woowacourse_java-lotto-6#5]
## 1. Feature

- 입력 기능

## 2. Tasks

- [x] 로또 구입 금액 입력 기능
- [x] 당첨 번호 입력 기능
    - [x] 번호는 쉼표를 기준으로 구분
- [x] 보너스 번호 입력 기능

## 3. Test

- [ ] 테스트 코드 작성 여부
