### ISSUE TITLE
출력 기능

### ISSUE THREAD

**Issue by Hyyena** [Hyyena/woowacourse_java-lotto-6#6]
## 1. Feature

- 입력 기능

## 2. Tasks

- [ ] 로또 수량 및 번호 출력
  - [ ] 로또 번호는 오름차순 정렬
- [ ] 당첨 내역 출력
- [ ] 수익률 출력

## 3. Test

- [ ] 테스트 코드 작성 여부
