### ISSUE TITLE
예외 처리

### ISSUE THREAD

**Issue by Hyyena** [Hyyena/woowacourse_java-lotto-6#7]
## 1. Feature

- 예외 처리

## 2. Tasks

- [x] `Exception`이 아닌 `IllegalArgumentException`, `IllegalStateException` 등과 같은 명확한 유형을 처리한다.
- [x] 예외 상황 시 에러 문구 출력
  - [x] 에러 문구는 `"[ERROR]"`로 시작

## 3. Test

- [x] 테스트 코드 작성 여부
